/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OperationLogDO implements Serializable {

    private static final long serialVersionUID = 1L;

    private LocalDateTime operationTime;
    private String operator;
    private String operationType;

    public OperationLogDO() {}

    public OperationLogDO(OperationLogDO value) {
        this.operationTime = value.operationTime;
        this.operator = value.operator;
        this.operationType = value.operationType;
    }

    public OperationLogDO(
        LocalDateTime operationTime,
        String operator,
        String operationType
    ) {
        this.operationTime = operationTime;
        this.operator = operator;
        this.operationType = operationType;
    }

    /**
     * Getter for <code>wpg.operation_log.operation_time</code>.
     */
    public LocalDateTime getOperationTime() {
        return this.operationTime;
    }

    /**
     * Setter for <code>wpg.operation_log.operation_time</code>.
     */
    public void setOperationTime(LocalDateTime operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * Getter for <code>wpg.operation_log.operator</code>.
     */
    public String getOperator() {
        return this.operator;
    }

    /**
     * Setter for <code>wpg.operation_log.operator</code>.
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * Getter for <code>wpg.operation_log.operation_type</code>.
     */
    public String getOperationType() {
        return this.operationType;
    }

    /**
     * Setter for <code>wpg.operation_log.operation_type</code>.
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OperationLogDO other = (OperationLogDO) obj;
        if (this.operationTime == null) {
            if (other.operationTime != null)
                return false;
        }
        else if (!this.operationTime.equals(other.operationTime))
            return false;
        if (this.operator == null) {
            if (other.operator != null)
                return false;
        }
        else if (!this.operator.equals(other.operator))
            return false;
        if (this.operationType == null) {
            if (other.operationType != null)
                return false;
        }
        else if (!this.operationType.equals(other.operationType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.operationTime == null) ? 0 : this.operationTime.hashCode());
        result = prime * result + ((this.operator == null) ? 0 : this.operator.hashCode());
        result = prime * result + ((this.operationType == null) ? 0 : this.operationType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OperationLogDO (");

        sb.append(operationTime);
        sb.append(", ").append(operator);
        sb.append(", ").append(operationType);

        sb.append(")");
        return sb.toString();
    }
}
