/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db;


import com.example.wpg.db.tables.Operator;
import com.example.wpg.db.tables.records.OperatorRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in wpg.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OperatorRecord> OPERATOR_PK = Internal.createUniqueKey(Operator.OPERATOR, DSL.name("operator_pk"), new TableField[] { Operator.OPERATOR.ID }, true);
}
