/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db;


import com.example.wpg.db.tables.TOperator;


/**
 * Convenience access to all tables in wpg.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>wpg.operator</code>.
     */
    public static final TOperator OPERATOR = TOperator.OPERATOR;
}
