/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db;


import com.example.wpg.db.tables.TOperator;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wpg extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>wpg</code>
     */
    public static final Wpg WPG = new Wpg();

    /**
     * The table <code>wpg.operator</code>.
     */
    public final TOperator OPERATOR = TOperator.OPERATOR;

    /**
     * No further instances allowed
     */
    private Wpg() {
        super("wpg", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TOperator.OPERATOR
        );
    }
}
