server:
  port: 8080
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: whatever
  data:
    redis:
      host: localhost
      port: 6379