/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db.tables.records;


import com.example.wpg.db.tables.TOperationLog;
import com.example.wpg.db.tables.pojos.OperationLogDO;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OperationLogRecord extends TableRecordImpl<OperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>wpg.operation_log.operation_time</code>.
     */
    public void setOperationTime(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>wpg.operation_log.operation_time</code>.
     */
    public LocalDateTime getOperationTime() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>wpg.operation_log.operator</code>.
     */
    public void setOperator(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wpg.operation_log.operator</code>.
     */
    public String getOperator() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wpg.operation_log.operation_type</code>.
     */
    public void setOperationType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wpg.operation_log.operation_type</code>.
     */
    public String getOperationType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperationLogRecord
     */
    public OperationLogRecord() {
        super(TOperationLog.OPERATION_LOG);
    }

    /**
     * Create a detached, initialised OperationLogRecord
     */
    public OperationLogRecord(LocalDateTime operationTime, String operator, String operationType) {
        super(TOperationLog.OPERATION_LOG);

        setOperationTime(operationTime);
        setOperator(operator);
        setOperationType(operationType);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OperationLogRecord
     */
    public OperationLogRecord(OperationLogDO value) {
        super(TOperationLog.OPERATION_LOG);

        if (value != null) {
            setOperationTime(value.getOperationTime());
            setOperator(value.getOperator());
            setOperationType(value.getOperationType());
            resetChangedOnNotNull();
        }
    }
}
