/*
 * This file is generated by jOOQ.
 */
package com.example.wpg.db.tables.records;


import com.example.wpg.db.tables.TOperator;
import com.example.wpg.db.tables.pojos.OperatorDO;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OperatorRecord extends UpdatableRecordImpl<OperatorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>wpg.operator.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>wpg.operator.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>wpg.operator.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>wpg.operator.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wpg.operator.tel</code>.
     */
    public void setTel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>wpg.operator.tel</code>.
     */
    public String getTel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>wpg.operator.addr</code>.
     */
    public void setAddr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>wpg.operator.addr</code>.
     */
    public String getAddr() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperatorRecord
     */
    public OperatorRecord() {
        super(TOperator.OPERATOR);
    }

    /**
     * Create a detached, initialised OperatorRecord
     */
    public OperatorRecord(String id, String name, String tel, String addr) {
        super(TOperator.OPERATOR);

        setId(id);
        setName(name);
        setTel(tel);
        setAddr(addr);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OperatorRecord
     */
    public OperatorRecord(OperatorDO value) {
        super(TOperator.OPERATOR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setTel(value.getTel());
            setAddr(value.getAddr());
            resetChangedOnNotNull();
        }
    }
}
